# Referencias


- Centro Magis (2025). _Material del curso Métodos y Simulación, versión 01-2025_. Maestría en Ciencia de Datos, Pontificia Universidad Javeriana Cali, Facultad de Ingeniería.

- Little, R. J. A. (1988). A test of missing completely at random for multivariate data with missing values. _Journal of the American Statistical Association_, 83(404), 1198–1202.

- Little, R. J. A. y Rubin, D. B. (2002). _Statistical Analysis with Missing Data_ (2.ª ed.). Wiley.

- Rubin, D. B. (1987). _Multiple Imputation for Nonresponse in Surveys_. Wiley.

- Sotaquirá, M. [Codificando Bits]. _Tutorial: ANÁLISIS EXPLORATORIO DE DATOS con Python_  [Video]. YouTube. https://www.youtube.com/watch?v=wBu0hQQVdcE

- Sotaquirá, M. [Codificando Bits]. _Tutorial: MANEJO DE DATOS CATEGÓRICOS FALTANTES con Python, Pandas y Scikit-Learn_ [Video]. YouTube. https://www.youtube.com/watch?v=G3tNCSQUoXw

- Sotaquirá, M. [Codificando Bits]. _¿Cómo hacer el ANÁLISIS EXPLORATORIO DE DATOS?: guía paso a paso_ [Video]. YouTube. https://www.youtube.com/watch?v=_-KW4gT_oGU

- van Buuren, S. y Groothuis-Oudshoorn, K. (2011). mice: Multivariate Imputation by Chained Equations in R. _Journal of Statistical Software_, 45(3), 1–67. https://doi.org/10.18637/jss.v045.i03

- van Buuren, S. (2018). _Flexible Imputation of Missing Data_ (2.ª ed.). Chapman and Hall/CRC. https://doi.org/10.1201/9780429492259

- Tukey, J. W. (1977). _Exploratory Data Analysis_. Addison-Wesley.

- Wickham, H. (2014). Tidy Data. _Journal of Statistical Software_, 59(10), 1–23. https://doi.org/10.18637/jss.v059.i10
